export const COLLECTION_FETCH_PLAYLISTS = 'COLLECTION_FETCH_PLAYLISTS';
export const COLLECTION_SAVE_PLAYLISTS = 'COLLECTION_SAVE_PLAYLISTS';
export const COLLECTION_SHOW_PLAYLIST = 'COLLECTION_SHOW_PLAYLIST';
