const fakePlaylists = [
	{ id: 0, label: 'No. 1 Hits 1970s-2000s' },
	{ id: 1, label: 'No. 1 Hits 1990-95' },
	{ id: 2, label: 'No. 1 Rap Hits' },
	{ id: 3, label: 'No. 1 Rock Hits!' },
	{ id: 4, label: 'BadGirls' },
	{ id: 5, label: 'Hot100: April \'15' },
	{ id: 6, label: 'Hot100: February \'15' },
	{ id: 7, label: 'Hot100: January \'15' },
	{ id: 8, label: 'Hot100: July \'15' },
	{ id: 9, label: 'Hot100: June \'15' },
	{ id: 10, label: 'Hot100: March \'15' },
	{ id: 11, label: 'Hot100: May \'15' },
	{ id: 12, label: 'Hot100: November \'15' },
	{ id: 13, label: 'instaGLAM' },
	{ id: 14, label: 'trendingtunes Summer 2014' },
	{ id: 15, label: '1960s No. 1 Hits!' },
	{ id: 16, label: '1960\'s Pop!' },
	{ id: 17, label: '1960\'s Rock!' },
	{ id: 18, label: '1970\'s No. 1 Hits!' },
	{ id: 19, label: '1970\'s Pop!' },
	{ id: 20, label: '1970\'s Summers' },
	{ id: 21, label: '1970s-80s Rock' },
	{ id: 22, label: '1980\'s No. 1 Hits!' },
	{ id: 23, label: '1980\'s Soft Pop' },
	{ id: 24, label: '1990\'s No. 1 Hits!' },
	{ id: 25, label: '1990\'s FUN!' },
	{ id: 26, label: '2 Tone & Ska 1979-1984' },
	{ id: 27, label: '2-Step & Garage' },
	{ id: 28, label: '2000\'s Alternative' },
	{ id: 29, label: '2000\'s Country' },
	{ id: 30, label: '2000\'s Dance Party' },
	{ id: 31, label: '2000\'s Duets' },
	{ id: 32, label: '2000\'s Electronic' },
	{ id: 33, label: '2000\'s Folk Rock' },
	{ id: 34, label: '2000\'s Gold Records' },
	{ id: 35, label: '2000\'s Happy Pop!' },
	{ id: 36, label: '2000s Hard Rock' },
	{ id: 37, label: '2000\'s Heartthrobs' },
	{ id: 38, label: '2000\'s Hip-Hop' },
	{ id: 39, label: '2000\'s Hit Singles: A/B' },
	{ id: 40, label: '2000\'s Indie' },
	{ id: 41, label: '2000\'s Jukebox' },
	{ id: 42, label: '2000\'s Love Songs' },
	{ id: 43, label: '2000\'s Movie Songs' },
	{ id: 44, label: '2000\'s Pop' },
	{ id: 45, label: '2000\'s Pop Divas' },
	{ id: 46, label: '2000\'s R&B' },
	{ id: 47, label: '2000\'s Rap' },
	{ id: 48, label: '2000\'s Rock' },
	{ id: 49, label: '2000\'s Slow Jams' },
	{ id: 50, label: '2000\'s Soft Pop' },
	{ id: 51, label: '2013 Best Dance Songs' },
	{ id: 52, label: '2013 Best of Country' },
	{ id: 53, label: '2013 Best R&B/Hip Hop' },
	{ id: 54, label: '2013 Cool & New' },
	{ id: 55, label: '2013 Dance Party' },
	{ id: 56, label: '2013 Teen Party' },
	{ id: 57, label: '2013-14 Award Winning Pop' },
	{ id: 58, label: '2013-14 Top Country Hits' },
	{ id: 59, label: '2014 Award Nominees' },
	{ id: 60, label: '2014 Best Country' },
	{ id: 61, label: '2014 Best Electronic' },
	{ id: 62, label: '2014 Best Latin' },
	{ id: 63, label: '2014 Best Pop' },
	{ id: 64, label: '2014 Best Rap/R&B' },
	{ id: 65, label: '2014 Best Rock' },
	{ id: 66, label: '2014 In Memoriam' },
	{ id: 67, label: '2014 Soft Pop!' },
	{ id: 68, label: '2014 Teen Party' },
	{ id: 69, label: '2014 Teen Party (Spring)' },
	{ id: 70, label: '2014: New Year New You!' },
	{ id: 71, label: '2015 Grammy Nominees' },
	{ id: 72, label: '2Pac' },
	{ id: 73, label: '50 Cent' },
	{ id: 74, label: '50\'s Collection (US)' },
	{ id: 75, label: '50\'s Country Chart Toppers' },
	{ id: 76, label: '50s-80s Movie Song Awards' },
	{ id: 77, label: '60\'s British Invasion' },
	{ id: 78, label: '60\'s Collection' },
	{ id: 79, label: '60\'s Country' },
	{ id: 80, label: '60\'s Folk' },
	{ id: 81, label: '60\'s Garage Rock' },
	{ id: 82, label: '60\'s Girl Groups' },
	{ id: 83, label: '60\'s Hit Artists: A/B' },
	{ id: 84, label: '60\'s Love Songs' },
	{ id: 85, label: '60s Rock: US vs. UK' },
	{ id: 86, label: '60\'s-70\'s Jukebox' },
	{ id: 87, label: '60s-70s Rock!' },
	{ id: 88, label: '70\'s & 80\'s Heartthrob' },
	{ id: 89, label: '70\'s AM Radio' },
	{ id: 90, label: '70\'s Classics' },
	{ id: 91, label: '70s Country' },
	{ id: 92, label: '70\'s Disco Fever' },
	{ id: 93, label: '70\'s Flashback' },
	{ id: 94, label: '70\'s Glam Rock' },
	{ id: 95, label: '70\'s Hit Artists: A/B' },
	{ id: 96, label: '70\'s Jukebox' },
	{ id: 97, label: '70\'s Ladies of Country' },
	{ id: 98, label: '70\'s Love Songs' },
	{ id: 99, label: '70\'s Movie Songs' },
	{ id: 100, label: '70\'s Punk' },
	{ id: 101, label: '70s Rock: US vs. UK' },
	{ id: 102, label: '70\'s Singalongs' },
	{ id: 103, label: '70\'s Slow Dance' },
	{ id: 104, label: '70\'s-80\'s Supergroups' },
	{ id: 105, label: '70s-80s Hard Rock' },
	{ id: 106, label: '70s-80s Punk' },
	{ id: 107, label: '70\'s-90\'s Jukebox' },
	{ id: 108, label: '70\'s-90\'s Rock' },
	{ id: 109, label: '80\'s Alternative Rock' },
	{ id: 110, label: '80\'s Breakup Songs' },
	{ id: 111, label: '80\'s British Invasion' },
	{ id: 112, label: '80\'s Club Anthems' },
	{ id: 113, label: '80\'s Country' },
	{ id: 114, label: '80\'s Dance Hits' },
	{ id: 115, label: '80\'s Dance Party' },
	{ id: 116, label: '80\'s Deep Cuts' },
	{ id: 117, label: '80\'s Electro Dance' },
	{ id: 118, label: '80\'s Flashback' },
	{ id: 119, label: '80\'s Gold Records' },
	{ id: 120, label: '80\'s Guilty Pleasures' },
];
const fakeTracklist = [
	{ title: 'The Sign', artist: 'Ace Of Base' },
	{ title: 'I Don\'t Want To Miss A Thing', artist: 'Aerosmith' },
	{ title: 'Boogie Oogie Oogie', artist: 'A Taste Of Honey' },
	{ title: 'Fallin\'', artist: 'Alicia Keys' },
	{ title: 'No One', artist: 'Alicia Keys' },
	{ title: 'I Swear', artist: 'All-4-One' },
	{ title: 'I Just Want To Be Your Everything', artist: 'Andy Gibb' },
	{ title: 'Shadow Dancing', artist: 'Andy Gibb' },
	{ title: 'Ring My Bell', artist: 'Anita Ward' },
	{ title: 'Foolish', artist: 'Ashanti' },
	{ title: 'The Way We Were', artist: 'Barbra Streisand' },
	{ title: 'Let It Be', artist: 'The Beatles' },
	{ title: 'How Can You Mend A Broken Heart', artist: 'Bee Gees' },
	{ title: 'How Deep Is Your Love', artist: 'Bee Gees' },
	{ title: 'Night Fever', artist: 'Bee Gees' },
	{ title: 'Stayin\' Alive', artist: 'Bee Gees' },
	{ title: 'Irreplaceable', artist: 'Beyoncé' },
	{ title: 'Lean On Me', artist: 'Bill Withers' },
	{ title: 'Me And Mrs. Jones', artist: 'Billy Paul' },
	{ title: 'Will It Go Round In Circles', artist: 'Billy Preston' },
	{ title: 'Raindrops Keep Fallin\' On My Head', artist: 'B.J. Thomas' },
	{ title: 'I Gotta Feeling', artist: 'The Black Eyed Peas' },
	{ title: 'Call Me', artist: 'Blondie' },
	{ title: 'Livin\' On A Prayer', artist: 'Bon Jovi' },
	{ title: 'Tha Crossroads', artist: 'Bone Thugs-n-Harmony' },
	{ title: 'Total Eclipse Of The Heart', artist: 'Bonnie Tyler' },
	{ title: 'I\'ll Make Love To You', artist: 'Boyz II Men' },
	{ title: 'On Bended Knee', artist: 'Boyz II Men' },
	{ title: '(Everything I Do) I Do It For You', artist: 'Bryan Adams' },
	{ title: 'Love Will Keep Us Together', artist: 'Captain & Tennille' },
	{ title: 'You\'re So Vain', artist: 'Carly Simon' },
	{ title: 'It\'s Too Late', artist: 'Carole King' },
	{ title: 'Top Of The World', artist: 'Carpenters' },
	{ title: 'Believe', artist: 'Cher' },
	{ title: 'Half-Breed', artist: 'Cher' },
	{ title: 'Le Freak', artist: 'Chic' },
	{ title: 'Run It!', artist: 'Chris Brown' },
	{ title: 'Genie In A Bottle', artist: 'Christina Aguilera' },
	{ title: 'Arthur\'s Theme (Best That You Can Do)', artist: 'Christopher Cross' },
	{ title: 'Three Times A Lady', artist: 'The Commodores' },
	{ title: 'Karma Chameleon', artist: 'Culture Club' },
	{ title: 'Bad Day', artist: 'Daniel Powter' },
	{ title: 'Lost In Your Eyes', artist: 'Debbie Gibson' },
	{ title: 'You Light Up My Life', artist: 'Debby Boone' },
	{ title: 'Ain\'t No Mountain High Enough', artist: 'Diana Ross' },
	{ title: 'Love Hangover', artist: 'Diana Ross' },
	{ title: 'Upside Down', artist: 'Diana Ross' },
	{ title: 'Money For Nothing', artist: 'Dire Straits' },
	{ title: 'Bad Girls', artist: 'Donna Summer' },
	{ title: 'Hot Stuff', artist: 'Donna Summer' },
	{ title: 'McArthur Park', artist: 'Donna Summer' },
	{ title: 'Go Away Little Girl', artist: 'Donny Osmond' },
	{ title: 'Keep On Truckin\'', artist: 'Eddie Kendricks' },
	{ title: 'War', artist: 'Edwin Starr' },
	{ title: 'Crocodile Rock', artist: 'Elton John' },
	{ title: 'Island Girl', artist: 'Elton John' },
	{ title: 'Best Of My Love', artist: 'The Emotions' },
	{ title: 'Kiss You All Over', artist: 'Exile' },
	{ title: 'Rock Me Amadeus', artist: 'Falco' },
	{ title: 'London Bridge', artist: 'Fergie' },
	{ title: 'Right Round [Ft. Kesha]', artist: 'Flo Rida' },
	{ title: 'December, 1963 (Oh, What A Night)', artist: 'The Four Seasons' },
	{ title: 'Grease', artist: 'Frankie Valli' },
	{ title: 'My Sweet Lord', artist: 'George Harrison' },
	{ title: 'Rock Your Baby', artist: 'George McCrae' },
	{ title: 'Faith', artist: 'George Michael' },
	{ title: 'Midnight Train To Georgia', artist: 'Gladys Knight & The Pips' },
	{ title: 'Rhinestone Cowboy', artist: 'Glen Campbell' },
	{ title: 'I Will Survive', artist: 'Gloria Gaynor' },
	{ title: 'American Woman', artist: 'The Guess Who' },
	{ title: 'Hollaback Girl', artist: 'Gwen Stefani' },
	{ title: 'MMMBop', artist: 'Hanson' },
	{ title: 'Rise', artist: 'Herb Alpert' },
	{ title: 'Rock The Boat', artist: 'Hues Corporation' },
	{ title: 'Don\'t You Want Me', artist: 'The Human League' },
	{ title: 'Centerfold', artist: 'The J. Geils Band' },
	{ title: 'I\'ll Be There', artist: 'The Jackson 5' },
	{ title: 'All For You', artist: 'Janet Jackson' },
	{ title: 'Miss You Much', artist: 'Janet Jackson' },
	{ title: 'Me And Bobby McGee', artist: 'Janis Joplin' },
	{ title: 'If You Had My Love', artist: 'Jennifer Lopez' },
	{ title: 'Bad, Bad Leroy Brown', artist: 'Jim Croce' },
	{ title: 'Time In A Bottle', artist: 'Jim Croce' },
	{ title: 'Disco Lady', artist: 'Johnnie Taylor' },
	{ title: 'I Can See Clearly Now', artist: 'Johnny Nash' },
	{ title: 'SexyBack [Ft. Timbaland]', artist: 'Justin Timberlake' },
	{ title: 'I Kissed A Girl', artist: 'Katy Perry' },
	{ title: 'All My Life', artist: 'K-Ci & JoJo' },
	{ title: 'Footloose', artist: 'Kenny Loggins' },
	{ title: 'Lady', artist: 'Kenny Rogers' },
	{ title: 'Bette Davis Eyes', artist: 'Kim Carnes' },
	{ title: 'My Sharona', artist: 'The Knack' },
	{ title: 'Jump', artist: 'Kris Kross' },
	{ title: 'Bleeding Love', artist: 'Leona Lewis' },
	{ title: 'All Night Long (All Night)', artist: 'Lionel Richie' },
	{ title: 'Say You, Say Me', artist: 'Lionel Richie' },
	{ title: 'Like A Prayer', artist: 'Madonna' },
	{ title: 'Music', artist: 'Madonna' },
	{ title: 'Kiss And Say Goodbye', artist: 'The Manhattans' },
	{ title: 'Dreamlover', artist: 'Mariah Carey' },
	{ title: 'Fantasy', artist: 'Mariah Carey' },
	{ title: 'Hero', artist: 'Mariah Carey' },
	{ title: 'Love Takes Time', artist: 'Mariah Carey' },
	{ title: 'Vision Of Love', artist: 'Mariah Carey' },
	{ title: 'We Belong Together', artist: 'Mariah Carey' },
	{ title: 'Let Me Love You', artist: 'Mario' },
	{ title: 'Let\'s Get It On', artist: 'Marvin Gaye' },
	{ title: 'I\'d Do Anything For Love (But I Won\'t Do That)', artist: 'Meat Loaf' },
	{ title: 'Star Wars Theme/Cantina Band', artist: 'Meco' },
	{ title: 'Brand New Key', artist: 'Melanie' },
	{ title: 'Beat It', artist: 'Michael Jackson' },
	{ title: 'Billie Jean', artist: 'Michael Jackson' },
	{ title: 'Black Or White', artist: 'Michael Jackson' },
	{ title: 'The First Night', artist: 'Monica' },
	{ title: 'This Is How We Do It', artist: 'Montell Jordan' },
	{ title: 'Bad Blood', artist: 'Neil Sedaka' },
	{ title: 'Hot In Herre', artist: 'Nelly' },
	{ title: 'Too Close', artist: 'Next' },
	{ title: 'Hypnotize', artist: 'The Notorious B.I.G.' },
	{ title: 'Magic', artist: 'Olivia Newton-John' },
	{ title: 'Physical', artist: 'Olivia Newton-John' },
];
export default (inputCollectionData = {}, action = {}) => {
	let playlistId, playlistIdx, playlist, newPlaylist, bHasPlaylistPayload;
	let updatedCollectionData = {};
	switch (action.type) {
		case 'PLAYLISTS_FETCH_LIST':
			// Initialize collection if necessary
			if (inputCollectionData.bInit) {
				updatedCollectionData = inputCollectionData;
			} else {
				updatedCollectionData.playlists = fakePlaylists;
				updatedCollectionData.selectedId = 0;
				updatedCollectionData.bInit = true;
			}
			return updatedCollectionData;
		case 'PLAYLIST_SHOW':
			bHasPlaylistPayload =
				(action.payload && action.payload.playlist && action.payload.playlist.id);
			if (bHasPlaylistPayload) {
				playlistId = action.payload.playlist.id;
			} else {
				// No playlist in payload -> show first playlist
				playlistId = inputCollectionData.playlists[0].id;
			}
			// Update the selectedId
			updatedCollectionData = {
				...inputCollectionData,
				selectedId: playlistId,
			};
			// Copy over the tracklist if it doesn't already exist
			playlistIdx = playlistId;
			playlist = updatedCollectionData.playlists[playlistIdx];
			if (!playlist.hasOwnProperty('tracklist')) {
				playlist = { ...playlist, tracklist: fakeTracklist };
				updatedCollectionData.playlists = [
					...updatedCollectionData.playlists.slice(0, playlistIdx),
					playlist,
					...updatedCollectionData.playlists.slice(playlistIdx + 1),
				];
			}
			return updatedCollectionData;
		default:
			return inputCollectionData;
	}
};
